services:
  - type: web
    name: debugiq-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        fromGroup: org-secrets
    healthCheckPath: /docs
